[build-system] 
requires = ["setuptools>=61.0,<82", "wheel"] 
build-backend = "setuptools.build_meta" 
 
[project] 
name = "fedcore" 
version = "0.0.5.3" 
description = "Framework for model compression and automation" 
readme = "README.md" 
requires-python = ">=3.9,<3.12" 
 
authors = [ 
  { name = "FedCore team" } 
] 
 
license = { text = "BSD 3-Clause" } 
 
dependencies = [
    "absl-py",
    "accelerate",
    "aiohappyeyeballs",
    "aiohttp",
    "aiosignal",
    "alabaster",
    "alembic",
    "annotated-types",
    "antlr4-python3-runtime",
    "anytree",
    "astroid",
    "asttokens",
    "async-timeout",
    "attrs",
    "autodocsumm",
    "babel",
    "beartype",
    "bidict",
    "bitsandbytes",
    "bleach",
    "blinker",
    "blis",
    "bokeh",
    "catalogue",
    "catboost",
    "category-encoders",
    "certifi",
    "cffi",
    "chardet",
    "charset-normalizer",
    "click",
    "cloudpathlib",
    "cloudpickle",
    "coloredlogs",
    "colorlog",
    "comm",
    "confection",
    "contourpy",
    "cryptography",
    "cycler",
    "cymem",
    "dask",
    "datasets>=2.20",
    "datasetsforecast",
    "debugpy",
    "decorator",
    "depq",
    "deprecated",
    "dill",
    "distributed",
    "docutils",
    "duckdb",
    "ete3",
    "evaluate",
    "exceptiongroup",
    "executing",
    "farama-notifications",
    "fastai",
    "fastcore",
    "fastdownload",
    "fastprogress",
    "fasttransform",
    "fedot==0.7.5",
    "filelock",
    "flask",
    "flask-cors",
    "flask-socketio",
    "flatbuffers",
    "fonttools",
    "frozenlist",
    "fsspec",
    "func-timeout",
    "future",
    "gevent",
    "gevent-websocket",
    "graphviz",
    "greenlet",
    "grpcio",
    "gymnasium",
    "h11",
    "hf-xet",
    "huggingface-hub",
    "humanfriendly",
    "hydra-core",
    "hyperopt",
    "idna",
    "imageio",
    "imagesize",
    "imbalanced-learn",
    "imblearn",
    "importlib-metadata",
    "iniconfig",
    "iopt",
    "ipykernel",
    "ipython",
    "isort",
    "itsdangerous",
    "jedi",
    "jinja2",
    "joblib",
    "jsonpickle",
    "jupyter-client",
    "jupyter-core",
    "kaggle",
    "kiwisolver",
    "langcodes",
    "language-data",
    "lightgbm",
    "lightning-utilities",
    "llvmlite",
    "locket",
    "mabwiser",
    "mako",
    "marisa-trie",
    "markdown",
    "markdown-it-py",
    "markupsafe",
    "matplotlib",
    "matplotlib-inline",
    "mccabe",
    "mdurl",
    "ml-dtypes",
    "mpmath",
    "msgpack",
    "multidict",
    "multiprocess",
    "murmurhash",
    "narwhals",
    "nest-asyncio",
    "networkx",
    "neural-compressor",
    "neural-insights",
    "numba",
    "numpy<2",
    "omegaconf",
    "onnx",
    "onnxruntime",
    "onnxruntime-extensions",
    "opencv-python-headless",
    "opendatasets",
    "optuna",
    "packaging",
    "pandas",
    "parso",
    "partd",
    "pathos",
    "patsy",
    "pexpect",
    "pillow",
    "pip",
    "platformdirs",
    "plotly",
    "pluggy",
    "plum-dispatch",
    "pox",
    "ppft",
    "preshed",
    "prettytable",
    "prompt-toolkit",
    "propcache",
    "protobuf",
    "psutil",
    "ptyprocess",
    "pure-eval",
    "py-boost",
    "py-cpuinfo",
    "py4j",
    "pyaml",
    "pyarrow>=21",
    "pycocotools",
    "pycparser",
    "pydantic",
    "pydantic-core",
    "pygments",
    "pylint",
    "pymonad",
    "pynvml",
    "pyparsing",
    "pytest",
    "python-dateutil",
    "python-engineio",
    "python-slugify",
    "python-socketio",
    "pytorch-lifestream",
    "pytorch-lightning",
    "pytz",
    "pyvis",
    "pyyaml",
    "pyzmq",
    "readthedocs-sphinx-search",
    "regex",
    "requests",
    "rich",
    "safetensors",
    "salib",
    "schema",
    "scikit-base",
    "scikit-learn",
    "scikit-optimize",
    "scipy",
    "seaborn",
    "segmentation-models-pytorch",
    "sentencepiece",
    "setuptools<82",
    "shellingham",
    "simple-websocket",
    "six",
    "sktime",
    "smart-open",
    "snowballstemmer",
    "sortedcontainers",
    "spacy",
    "spacy-legacy",
    "spacy-loggers",
    "sphinx",
    "sphinx-rtd-theme",
    "sphinxcontrib-applehelp",
    "sphinxcontrib-details-directive",
    "sphinxcontrib-devhelp",
    "sphinxcontrib-htmlhelp",
    "sphinxcontrib-jquery",
    "sphinxcontrib-jsmath",
    "sphinxcontrib-qthelp",
    "sphinxcontrib-serializinghtml",
    "sqlalchemy",
    "srsly",
    "stable-baselines3<3",
    "stack-data",
    "statsmodels",
    "sympy",
    "tblib",
    "tdecomp",
    "tensorly",
    "testfixtures",
    "text-unidecode",
    "thegolem",
    "thinc",
    "threadpoolctl",
    "timm",
    "tokenizers",
    "tomli",
    "tomlkit",
    "toolz",
    "torch",
    "torch-pruning",
    "torchinfo",
    "torchmetrics",
    "torchvision",
    "tornado",
    "tqdm",
    "traitlets",
    "transformers",
    "treelite",
    "treelite-runtime",
    "triton",
    "typer",
    "typing",
    "typing-extensions",
    "tzdata",
    "ucimlrepo",
    "ujson",
    "urllib3",
    "utilsforecast",
    "uv",
    "wasabi",
    "wcwidth",
    "weasel",
    "webencodings",
    "werkzeug",
    "wrapt",
    "wsproto",
    "xgboost",
    "xlrd",
    "xxhash",
    "xyzservices",
    "yarl",
    "zict",
    "zipp",
    "zope-event",
    "zope-interface",
    "zss",
] 
 
[project.urls] 
Homepage = "https://github.com/v1docq/FedCore"